# permissions for end users to edit htcondors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: htcondor-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: htcondor-operator
    app.kubernetes.io/part-of: htcondor-operator
    app.kubernetes.io/managed-by: kustomize
  name: htcondor-editor-role
rules:
- apiGroups:
  - flux-framework.org
  resources:
  - htcondors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flux-framework.org
  resources:
  - htcondors/status
  verbs:
  - get
